// <auto-generated />
using System;
using DEWESDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DewesDB.Migrations
{
    [DbContext(typeof(DbScheduleContext))]
    partial class DbScheduleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DEWESDb.Table.DataSink", b =>
                {
                    b.Property<Guid>("DataSinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameLibrary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataSinkId");

                    b.ToTable("DataSink");
                });

            modelBuilder.Entity("DEWESDb.Table.DataSource", b =>
                {
                    b.Property<Guid>("DataSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameLibrary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataSourceId");

                    b.ToTable("DataSource");
                });

            modelBuilder.Entity("DEWESDb.Table.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataSinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EDataSourceFormat")
                        .HasColumnType("int");

                    b.Property<int>("EDataSourceType")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("DataSinkId");

                    b.HasIndex("DataSourceId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("DEWESDb.Table.Schedule", b =>
                {
                    b.HasOne("DEWESDb.Table.DataSink", "DataSink")
                        .WithMany()
                        .HasForeignKey("DataSinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEWESDb.Table.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
